#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

# Autostart
sxhkd &
$HOME/.config/polybar/launch.sh

# Set some bsp specific stuff
bspc monitor HDMI-0 -d I II III IV V 
bspc monitor DP-0 -d VI VII VIII IX X

# Gaps
bspc config window_gap 15
bspc config border_width 1

# Splits
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

# Pointer
bspc config pointer_follows_monitor true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Window rules
bspc rule -a firefox desktop='^1'