[module/tray-placeholder]
type = custom/text
content-background = ${color.bg}
content = " "
content-padding = 20

[module/gl_left]
type = custom/text
content-background = ${color.alpha}
content-foreground = ${color.bg}
content = 
content-font = 3

[module/gl_right]
type = custom/text
content-background = ${color.alpha}
content-foreground = ${color.bg}
content = 
content-font = 3

[module/workspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true
enable-scroll = true
format-padding = 1

icon-default = 

format = <label-state>
format-background = ${color.bg}
label-active = 
label-occupied = 
label-empty = 

label-empty-padding = 1
label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1

label-empty-foreground = ${color.fg}
label-active-foreground = ${color.nord6}
label-urgent-foreground = ${color.urgent}
label-occupied-foreground = ${color.fg}


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ;-       volume       -; ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/volume]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
format-volume-padding = 2
format-volume-background = ${color.bg}

label-volume = %percentage%%
label-volume-foreground = ${color.fg}

label-muted = "婢"
label-muted-background = ${color.bg}
label-muted-foreground = ${color.urgent}
label-muted-padding = 2

ramp-volume-0 = 奄
ramp-volume-1 = 奄
ramp-volume-2 = 奔
ramp-volume-3 = 奔
ramp-volume-4 = 墳
ramp-volume-5 = 墳
ramp-volume-6 = 

ramp-volume-foreground = ${color.fg}

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ;-     volume end     -; ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ;-      time/date     -; ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/date-icon]
type = custom/text
content-background = ${color.bg}
content-foreground = ${color.nord9}
content = 
content-font = 3

[module/date]
type = internal/date
interval = 1.0
label = %date%
label-padding-left = 1
label-padding-right = 2
label-background = ${color.bg}
label-foreground = ${color.fg}
date = %d/%m/%Y

ramp-date-0 = 

[module/time-icon]
type = custom/text
content-background = ${color.bg}
content-foreground = ${color.nord9}
content = 
content-font = 3

[module/time]
type = internal/date
interval = 1.0
label =  %time%
label-padding-left = 1
label-padding-right = 2
label-background = ${color.bg}
label-foreground = ${color.fg}
time = %k:%M

[module/title]
type = internal/xwindow

format = <label>
label = %title%
label-background = ${color.bg}

[module/cpu]
type = internal/cpu

interval = 1

format = <label>
format-background = ${color.bg}
format-foreground = ${color.fg}
format-padding = 1
format-prefix = 
format-prefix-foreground = ${color.nord9}

label = " %percentage%%"

[module/ram]
type = internal/memory

interval = 1

format = <label>
format-background = ${color.bg}
format-foreground = ${color.fg}
format-padding = 1
format-prefix = ﬙
format-prefix-foreground = ${color.nord9}

label = " %percentage_used%%"